name: WR

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: npm install

      - name: Run bot
        run: node index.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Debug env (optional)
        run: |
          echo "TOKEN OK"
          echo "CHAT_ID OK"
          echo "API_KEY OK"
